//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SF_Download.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SF_Download.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;jobInfo
        ///    xmlns=&quot;http://www.force.com/2009/06/asyncapi/dataload&quot;&gt;
        ///  &lt;operation&gt;query&lt;/operation&gt;
        ///  &lt;object&gt;ObjectName&lt;/object&gt;
        ///  &lt;concurrencyMode&gt;Parallel&lt;/concurrencyMode&gt;
        ///  &lt;contentType&gt;CSV&lt;/contentType&gt;
        ///&lt;/jobInfo&gt;.
        /// </summary>
        internal static string createAccountJob {
            get {
                return ResourceManager.GetString("createAccountJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///CREATE PROCEDURE sfi.sfi_insert_log_execution
        /// 
        ///	@action_code varchar(20)
        ///,	@started_on datetime
        ///,	@completed_on datetime
        ///,	@username varchar(50)
        ///,	@log_execution_id int OUT
        ///,	@ran_to_completion bit = 0
        ///,	@error_text varchar(8000) = null
        ///
        ///
        ///AS
        ///
        ///	INSERT 
        ///	INTO	sfi.sfi_log_execution(action_code, started_on, completed_on, username, ran_to_completion, error_text) 
        ///	VALUES	(@action_code, @started_on, @completed_on, @username, @ran_to_completion, @error_text) 
        ///
        ///	SET @log_execution_id = SCOPE_I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_insert_log_execution {
            get {
                return ResourceManager.GetString("sfi_create_proc_insert_log_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///CREATE PROCEDURE sfi.sfi_insert_log_task
        /// 
        ///	@log_execution_id int
        ///,	@task varchar(50)
        ///,	@task_notes varchar(50)
        ///,	@object_id int
        ///,	@object_name varchar(255)
        ///,	@download_method varchar(50)
        ///,	@integration_method varchar(50)
        ///,	@sf_job_id varchar(50)
        ///,	@sf_batch_id varchar(50)
        ///,	@started_on [datetime] 
        ///,	@completed_on [datetime] = null
        ///,	@error_text varchar(8000) = null
        ///,	@record_count int = null
        ///
        ///,	@log_task_id [int] OUT
        ///
        ///AS
        ///
        ///	declare @task_id int = (select task_id from sfi.sfi_look [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_insert_log_task {
            get {
                return ResourceManager.GetString("sfi_create_proc_insert_log_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create procedure sfi.sfi_insert_settings 
        ///
        ///	@is_sandbox bit
        ///,	@sf_username varchar(50)
        ///,	@sf_password varchar(50)
        ///,	@sf_token varchar(50)
        ///,	@download_new_objects bit
        ///,	@download_empty_objects bit
        ///,	@download_method varchar(50)
        ///,	@integration_method varchar(50)
        ///
        ///as
        ///
        ///declare @download_method_id int = (select download_method_id from sfi.sfi_lookup_download_methods where download_method = @download_method)
        ///declare @integration_method_id int = (select integration_method_id from sfi.sfi_lookup_integ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_insert_settings {
            get {
                return ResourceManager.GetString("sfi_create_proc_insert_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///CREATE PROCEDURE [sfi].[sfi_log_task_complete]
        /// 
        ///	@completed_on [datetime]
        ///,	@error_text varchar(8000)
        ///,	@record_count int
        ///,	@log_task_id int
        ///
        ///AS
        ///
        ///	UPDATE	sfi.sfi_log_task
        ///	SET		completed_on = @completed_on
        ///	,		error_text = @error_text 
        ///	,		record_count = @record_count 
        ///	WHERE	log_task_id = @log_task_id
        ///
        ///.
        /// </summary>
        internal static string sfi_create_proc_log_task_complete {
            get {
                return ResourceManager.GetString("sfi_create_proc_log_task_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///
        ///create procedure [sfi].[sfi_select_changed_datatype_fields]
        ///
        ///	@log_execution_id int
        ///
        ///as
        ///
        ///select	* 
        ///from	
        ///		(
        ///		select	le.log_execution_id
        ///		,		ct.name change_type
        ///		,		fh.object_name	
        ///		,		fh.name	
        ///		,		fh.label	
        ///		,		fh.soap_type	
        ///		,		fh.byte_length	
        ///		,		fh.digits	
        ///		,		fh.is_deleted	
        ///		,		fh.download
        ///		,		fh.type	
        ///		,		fh.length	
        ///		,		fh.precision	
        ///		,		fh.scale
        ///		,		lag(fh.type) over (partition by fh.object_name, fh.name order by le.log_execution_id asc) type_previous
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_select_changed_datatype_fields {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_changed_datatype_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE procedure [sfi].[sfi_select_downloadable_objects]
        ///as
        ///
        ///select	o.object_id
        ///,		o.name
        ///,		o.is_queryable
        ///,		o.cant_query
        ///,		o.is_deleted
        ///,		o.is_empty
        ///,		o.download
        ///,		dm.download_method
        ///,		im.integration_method
        ///,		o.bulk_query_batch_size
        ///,		old.last_download_on
        ///from	sfm.sfm_objects o
        ///		join sfi.sfi_lookup_download_methods dm
        ///			on o.download_method = dm.download_method_id
        ///		join sfi.sfi_lookup_integration_methods im
        ///			on o.integration_method = im.integration_method_id
        ///		left join sfi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_select_downloadable_objects {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_downloadable_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create procedure [sfi].[sfi_select_empty_objects]
        ///as
        ///
        ///
        ///select	o.object_id
        ///,		o.name
        ///,		o.is_queryable
        ///,		o.cant_query
        ///,		o.is_deleted
        ///,		o.is_empty
        ///,		o.download
        ///,		dm.download_method
        ///,		im.integration_method
        ///,		o.bulk_query_batch_size 
        ///from	sfm.sfm_objects o
        ///		join sfi.sfi_lookup_download_methods dm
        ///			on o.download_method = dm.download_method_id
        ///		join sfi.sfi_lookup_integration_methods im
        ///			on o.integration_method = im.integration_method_id
        ///where	o.is_queryable = 1
        ///and		o.cant_query  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_select_empty_objects {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_empty_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create procedure sfi.sfi_select_new_fields
        ///
        ///	@log_execution_id int
        ///
        ///as
        ///
        ///select	fh.object_name	
        ///,		fh.name	
        ///,		fh.label	
        ///,		fh.soap_type	
        ///,		fh.type	
        ///,		fh.length	
        ///,		fh.byte_length	
        ///,		fh.digits	
        ///,		fh.precision	
        ///,		fh.scale	
        ///,		fh.is_autonumber	
        ///,		fh.is_calculated	
        ///,		fh.is_case_sensitive	
        ///,		fh.is_custom	
        ///,		fh.is_dependent_pick_list	
        ///,		fh.is_external_id	
        ///,		fh.is_ID_lookup	
        ///,		fh.is_name_field	
        ///,		fh.is_unique	
        ///,		fh.is_restricted_picklist	
        ///,		fh.is_deleted	
        ///,		fh.download
        ///f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_select_new_fields {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_new_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create procedure [sfi].[sfi_select_new_objects]
        ///
        ///	@log_execution_id as int
        ///
        ///as
        ///
        ///select	*
        ///from	sfm.sfm_objects_history h
        ///		join sfi.sfi_lookup_change_types ct
        ///			on h.change_type_id = ct.change_type_id
        ///		join sfi.sfi_log_task lt
        ///			on h.log_task_id = lt.log_task_id
        ///where	ct.name = &apos;New Object&apos;
        ///and		lt.log_execution_id = @log_execution_id
        ///and		h.is_queryable = 1
        ///
        ///.
        /// </summary>
        internal static string sfi_create_proc_select_new_objects {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_new_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create procedure [sfi].[sfi_select_object_fields]
        ///
        ///	@object_name varchar(255)
        ///,	@download bit = null
        ///
        ///as
        ///
        ///select	f.field_id	
        ///,		f.object_id	
        ///,		o.name object_name
        ///,		f.name	
        ///,		f.label	
        ///,		f.soap_type	
        ///,		f.type	
        ///,		f.length	
        ///,		f.byte_length	
        ///,		f.digits	
        ///,		f.precision	
        ///,		f.scale	
        ///,		f.is_autonumber	
        ///,		f.is_calculated	
        ///,		f.is_case_sensitive	
        ///,		f.is_custom	
        ///,		f.is_dependent_pick_list	
        ///,		f.is_external_id	
        ///,		f.is_ID_lookup	
        ///,		f.is_name_field	
        ///,		f.is_unique	
        ///,		f.is_restri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_select_object_fields {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_object_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///create procedure [sfi].[sfi_select_object_settings]
        ///
        ///	@object_name varchar(255)
        ///
        ///as
        ///
        ///select	o.object_id	
        ///,		o.name object_name
        ///,		o.cant_query
        ///,		o.cant_query_error
        ///,		o.is_deleted
        ///,		o.is_empty
        ///,		o.download
        ///,		dm.download_method
        ///,		im.integration_method
        ///,		o.is_deleted
        ///from	sfm.sfm_objects o
        ///		join sfi.sfi_lookup_download_methods dm
        ///			on o.download_method = dm.download_method_id
        ///		join sfi.sfi_lookup_integration_methods im
        ///			on o.integration_method = im.integration_method_id
        ///where [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_select_object_settings {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_object_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create procedure sfi.sfi_select_settings
        ///as
        ///
        ///select	s.is_sandbox
        ///,		s.sf_username
        ///,		s.sf_password
        ///,		s.sf_token
        ///,		s.download_new_objects
        ///,		s.download_empty_objects
        ///,		dm.download_method
        ///,		im.integration_method
        ///from	sfi.sfi_settings s
        ///		join sfi.sfi_lookup_download_methods dm
        ///			on s.download_method_id = dm.download_method_id
        ///		join sfi.sfi_lookup_integration_methods im
        ///			on s.integration_method_id = im.integration_method_id.
        /// </summary>
        internal static string sfi_create_proc_select_settings {
            get {
                return ResourceManager.GetString("sfi_create_proc_select_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create procedure [sfi].[sfi_table_exists]
        ///
        ///	@schema_name varchar(50)
        ///,	@table_name varchar(255)
        ///
        ///as
        ///
        ///if OBJECT_ID(@schema_name + &apos;.&apos; + @table_name, &apos;U&apos;) is null return 0 else return 1
        ///.
        /// </summary>
        internal static string sfi_create_proc_table_exists {
            get {
                return ResourceManager.GetString("sfi_create_proc_table_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///create procedure [sfi].[sfi_update_field_download_status]
        ///
        ///	@log_task_id int
        ///,	@object_name varchar(255)
        ///,	@field_name varchar(255)
        ///,	@download bit
        ///
        ///as
        ///
        ///declare @change_type_id int = (select change_type_id from sfi.sfi_lookup_change_types where name = &apos;Update Field Download Status&apos;)
        ///
        ///insert into sfm.sfm_fields_history
        ///select	@log_task_id
        ///,		@change_type_id
        ///,		o.name	
        ///,		f.name	
        ///,		f.label	
        ///,		f.soap_type	
        ///,		f.type	
        ///,		f.length	
        ///,		f.byte_length	
        ///,		f.digits	
        ///,		f.precision	
        ///,		f. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_update_field_download_status {
            get {
                return ResourceManager.GetString("sfi_create_proc_update_field_download_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROCEDURE sfi.sfi_update_log_execution
        ///  
        ///	@started_on datetime
        ///,	@completed_on datetime
        ///,	@username varchar(50)
        ///,	@log_execution_id int
        ///,	@ran_to_completion bit 
        ///,	@error_text varchar(8000) = null
        ///
        ///
        ///AS
        ///
        ///	UPDATE	sfi.sfi_log_execution
        ///	SET		started_on = @started_on
        ///	,		completed_on = @completed_on
        ///	,		username = @username
        ///	,		ran_to_completion = @ran_to_completion
        ///	,		error_text = @error_text
        ///	WHERE	log_execution_id = @log_execution_id
        ///
        ///
        ///.
        /// </summary>
        internal static string sfi_create_proc_update_log_execution {
            get {
                return ResourceManager.GetString("sfi_create_proc_update_log_execution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///CREATE PROCEDURE sfi.sfi_update_log_task
        /// 
        ///	@download_method varchar(50)
        ///,	@integration_method varchar(50)
        ///,	@sf_job_id varchar(50)
        ///,	@sf_batch_id varchar(50)
        ///,	@completed_on [datetime]
        ///,	@error_text varchar(8000)
        ///,	@record_count int
        ///,	@log_task_id int
        ///
        ///AS
        ///	declare @download_method_id int = (select download_method_id from sfi.sfi_lookup_download_methods where download_method = @download_method)
        ///	declare @integration_method_id int = (select integration_method_id from sfi.sfi_lookup_integration [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_update_log_task {
            get {
                return ResourceManager.GetString("sfi_create_proc_update_log_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///create procedure [sfi].[sfi_update_meta_data]
        ///
        ///	@log_task_id int
        ///
        ///as
        ///
        ///	
        ///	----------------OBJECTS-----------------
        ///	declare @new_change_id int = (select change_type_id from sfi.sfi_lookup_change_types where name = &apos;New Object&apos;)
        ///	declare @delete_change_id int = (select change_type_id from sfi.sfi_lookup_change_types where name = &apos;Delete Object&apos;)
        ///
        ///
        ///	/* 
        ///		Add deleted objects to the history
        ///
        ///		If an object name exists in objects that is not flagged as deleted and does not
        ///		exist in object_t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_update_meta_data {
            get {
                return ResourceManager.GetString("sfi_create_proc_update_meta_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///CREATE procedure [sfi].[sfi_update_object_download_status]
        ///
        ///	@log_task_id int
        ///,	@object_name varchar(255)
        ///,	@cant_query bit = null
        ///,	@cant_query_error varchar(8000) = null
        ///,	@is_empty bit = null
        ///,	@download bit = null
        ///,	@download_method varchar(50) = null
        ///,	@integration_method varchar(50) = null
        ///,	@bulk_query_batch_size int = null
        ///
        ///
        ///as
        ///
        ///
        ///declare @change_type_id int = (select change_type_id from sfi.sfi_lookup_change_types where name = &apos;Update Object Download Status&apos;)
        ///declare @download_m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_proc_update_object_download_status {
            get {
                return ResourceManager.GetString("sfi_create_proc_update_object_download_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE view [sfm].[sfm_fields_history_v]
        ///as
        ///select	le.log_execution_id
        ///,		le.action_code
        ///,		le.started_on execution_started_on
        ///,		lt.started_on task_started_on
        ///,		lt.task_id
        ///,		lkt.task task_name
        ///,		ct.name change_type
        ///,		fh.object_name
        ///,		fh.name field_name
        ///,		fh.label
        ///,		fh.soap_type
        ///,		fh.type
        ///,		fh.length
        ///,		fh.byte_length
        ///,		fh.digits
        ///,		fh.precision
        ///,		fh.scale
        ///,		fh.is_autonumber
        ///,		fh.is_calculated
        ///,		fh.is_case_sensitive
        ///,		fh.is_custom
        ///,		fh.is_dependent_pick_list
        ///,		fh.is_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_view_fields_history {
            get {
                return ResourceManager.GetString("sfi_create_view_fields_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view sfi.sfi_object_last_download_v
        ///as
        ///select	t.object_id
        ///,		t.object_name
        ///,		max(t.started_on) last_download_on
        ///from	sfi.sfi_log_execution e
        ///		join sfi.sfi_log_task t
        ///			on e.log_execution_id = t.log_execution_id
        ///		join sfi.sfi_lookup_tasks lt
        ///			on t.task_id = lt.task_id
        ///where	e.ran_to_completion = 1
        ///and		e.action_code = &apos;Download&apos;
        ///and		lt.task = &apos;Download Object Data&apos;
        ///group by t.object_id
        ///,		t.object_name
        ///.
        /// </summary>
        internal static string sfi_create_view_object_last_download {
            get {
                return ResourceManager.GetString("sfi_create_view_object_last_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///create view [sfm].[sfm_objects_history_v]
        ///as
        ///select	le.log_execution_id
        ///,		le.action_code
        ///,		le.started_on execution_started_on
        ///,		lt.started_on task_started_on
        ///,		lt.task_id
        ///,		lkt.task task_name
        ///,		ct.name change_type
        ///,		oh.key_prefix
        ///,		oh.name object_name
        ///,		oh.label
        ///,		oh.is_custom
        ///,		oh.is_custom_setting
        ///,		oh.is_queryable
        ///,		oh.cant_query
        ///,		oh.cant_query_error
        ///,		oh.is_deleted
        ///,		oh.download
        ///,		oh.bulk_query_batch_size
        ///,		dm.download_method
        ///,		im.integration_method
        ///from	sfm.s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfi_create_view_objects_history {
            get {
                return ResourceManager.GetString("sfi_create_view_objects_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///CREATE TABLE [sfi].[sfi_settings](
        ///	[is_sandbox] [bit] NULL,
        ///	[sf_username] [varchar](50) NULL,
        ///	[sf_password] [varchar](50) NULL,
        ///	[sf_token] [varchar](50) NULL,
        ///	download_new_objects bit null,
        ///	download_empty_objects [bit] NULL,
        ///	download_method_id int null,
        ///	integration_method_id int null
        ///
        ///) 
        ///
        ///
        ///CREATE TABLE sfi.sfi_log_execution
        ///( 
        ///	log_execution_id int identity(1,1) primary key clustered
        ///,	action_code varchar(20)
        ///,	started_on datetime
        ///,	completed_on datetime
        ///,	username varchar(5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sfm_create_tables {
            get {
                return ResourceManager.GetString("sfm_create_tables", resourceCulture);
            }
        }
    }
}
